version: '3.8'

services:
  ollama:
    build:
      context: ../ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - llmagent-network

  llmagent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    depends_on:
      - ollama
    networks:
      - llmagent-network

networks:
  llmagent-network:
    driver: bridge 